### PR TITLE
Add support for hashed passwords

### PR DESCRIPTION
**Pull request by sebakerckhof**

### CODE REVIEW

**Comment by kahmali** [comment]
I don't think I want to add anymore complexity to the auth in the core Restivus package. What really needs to happen is that I need to modularize Restivus so that the auth can be completely overridden by other packages. Then this type of code would just be contained in a separate package which users could choose to add to their app as needed, instead of bloating the default auth with a bunch of checks that the majority of clients won't need when authenticating. 

If you want to help me modularize the auth I would certainly appreciate that, as I have almost no time to work on Restivus nowadays. While the code here looks good and I love the idea of giving folks more options for authentication, I don't think that I'll pull this into the core Restivus. Sorry about that. Feel free to discuss this or any ideas further with me. You seem like you know a lot more about authentication than I do, and I always love to learn more about the topic. Thanks for submitting the PR!

**Comment by santiq** [comment]
I'm agreed with the need of modularize Restivus!
But, in this case, I think this is an important feature and it would be great if is a part of the core authentication because it leads to good practices and enforce the security

**Comment by kahmali** [comment]
I changed my mind – I am going to pull this PR in. Working on getting a bunch of PRs merged and I'll include this one with that effort.

**Comment by kahmali** [comment]
I'm going to merge this PR in with some others shortly. Just a heads up.

**Comment by kahmali** [comment]
Just merged this in with some other PRs and published it in [v0.8.12](https://github.com/kahmali/meteor-restivus/blob/devel/CHANGELOG.md#v0812---2017-01-23).

Thanks so much for the contribution!

**Comment by lukecampbell** [comment]
I just wanted to reach out and say thanks for this, this helps so much!

**Pull request merged**
