### PR TITLE
it's -> its

### PR DESCRIPTION
**Pull request by dandv**

### CODE REVIEW

**Comment by kahmali** [comment]
I'm very particular about [commit messages](https://github.com/kahmali/meteor-restivus/blob/master/CONTRIBUTING.md#commit-messages), and this one definitely didn't pass the test. Instead of having you waste time resubmitting this pull request over that, when only a single word was changed in the docs, I just snuck this update in when I added the information on contributing. Thanks for catching the error. My English professor would be ashamed of me if he ever found out. I'll go ahead and close this.

**Comment by dandv** [comment]
Wow, LOL, OK :) I thought *I* was [OCD](http://wiki.dandascalescu.com/bugs) :)

BTW, how did my other commits make it, since they were on master vs. dev?

**Comment by kahmali** [comment]
Haha. That really is a special talent! I guess I'm _slightly_ more convinced that you're not actually a band of magical programming elves. I'm always amazed at how active you are in the Meteor community, and I see now it's not just limited to Meteor. Geez! Keep up the great work!

To answer your question, here's an excerpt from my new [Contributing Guidelines](https://github.com/kahmali/meteor-restivus/blob/master/CONTRIBUTING.md#pull-requests): 

_All pull requests should be made to the `dev` branch, unless **all** changes in the request are to
the README or CHANGELOG **and** all of those changes are already reflected in the latest released
version. If that's the case, the pull request should be made to `master`._

**Comment by kahmali** [comment]
After thinking about it some more, the workflow I described will cause syncing issues in downstream repos, as it requires me to rewrite the commit history that some folks may have based local branches off of whenever I rebase `dev` onto `master`. I realized that when I'm using this workflow on my own, I always rebase onto dev first, then master. I don't know how I had this temporary lapse in judgment. 

I'll have to create an issue when I rebase dev this time to warn everyone that they will need to force an update from upstream before making any additional changes. I feel like a terrible person for this. That was very bad git practice, and I should know better. Shame on me. I'll rectify this asap.

**Comment by kahmali** [comment]
Okay, I went ahead and forced that update. I can't apologize enough for my stupid mistake. I'm going to update the workflow in the Contributing Guidelines. Just force an update of the dev branch using [this technique](http://stackoverflow.com/questions/9813816/git-pull-after-forced-update) before you make any further changes.

**Comment by dandv** [comment]
> I feel like a terrible person for this. That was very bad git practice, and I should know better. Shame on me. I'll rectify this asap.

Go stand in a corner!! ;-)

Was this by any chance the cause for [this commit](https://github.com/kahmali/meteor-restivus/commit/b726db9edf18b0b715788e350fffad3851a5d951) appearing as written by @raix? The style of CONTRIBUTING.md is very much yours, and [his recent activity](https://github.com/raix) shows no commits for the past several days.

**Comment by kahmali** [comment]
Ah, yes! That was _me_, not @raix making those commits, but it was actually unrelated.

Sorry for accidentally masquerading as you in a few commits @raix! 

I have the privilege of working with him, and he was in town last week. I was having a problem with the environment on my laptop and he cloned his [dotfiles](https://github.com/raix/dotfiles) repo on my machine to alleviate some of my configuration issues. One of those files is a .gitconfig that set @raix as the global git user on my machine. So without realizing, I was committing under his name for a few days. It should be fixed though. :)

**Pull request closed without merging**
