### PR TITLE
Add support for JSON PATCH

### PR DESCRIPTION
**Pull request by azemoh**
Fixes Issue #207

### CODE REVIEW

**Comment by kahmali** [comment]
Looks good at first glance. I haven't given this repo any love in a very very long time, but I plan to devote a day to it this coming week and I promise that I'll pull this in and publish an update. There are a few lingering PRs that can be pulled in, actually. 

Just a note: what you've added here isn't true [JSON PATCH](http://jsonpatch.com/) support. It's still PATCH support however, and it's definitely better than nothing. Thanks for the contribution! I'll keep you posted on pulling it in, and feel free to yell at me if you don't hear back by the end of next weekend.

**Comment by azemoh** [comment]
Thanks for pointing that out. I'll probably raise a PR for proper JSON PATCH support when I fully understand it.

**Comment by kahmali** [comment]
Awesome! Looking forward to it!

**Comment by azemoh** [comment]
Hey @kahmali, this is me yelling... 😃

**Comment by kahmali** [comment]
Duly noted @azemoh 😄. I spent some time Saturday going through the pending PRs chronologically. Unfortunately, that put this PR at the end of the line, and I never got around to it. Gonna spend some time today on Restivus and I should get it pulled in. Thanks for checking in. I'll keep you posted.

**Comment by azemoh** [comment]
Sure thing. And yeah I see you resolved and raised some issues.

**Comment by kahmali** [comment]
Just merged this in with some other PRs and published it in [v0.8.12](https://github.com/kahmali/meteor-restivus/blob/devel/CHANGELOG.md#v0812---2017-01-23).

Thanks so much for the contribution!

**Pull request merged**
