### PR TITLE
Replace iron:router with simple:json-routes

### PR DESCRIPTION
**Pull request by stubailo**
I can work on adding the catchall route to `/api` after this, seems like a good idea.

### CODE REVIEW

**Comment by kahmali** [comment]
You are too fast for me! I forgot one thing that I'm _almost_ too embarrassed to ask. I decided that I'm not too embarrassed to ask, but you are definitely awesome enough that I _will_ accept a denial of my seemingly trivial request, especially since I forgot to mention it in the other PR. 

I have terrible OCD as you'll see if you check my commit messages in this repo. You'll see that I adhere to a standard that I never break, which is the 50/72, imperative-style commit messages, which I mention in my [Contributing](https://github.com/kahmali/meteor-restivus/blob/master/CONTRIBUTING.md#commit-messages) doc. 

So if you could somehow change that first commit message to "Replace iron:router with simple:json-routes", that should fix everything and help me sleep much better at night. However, I realize you're incredibly busy, and I'm new to the PR workflow, so I'm not sure how annoying a change this is. So since I've already wasted enough of your time making you read this request, please feel free to just say, "way too busy", and I'll just pull these right in. If I knew how to edit it myself without writing a different commit history than your own, I would. Like I said, very new to the PR workflow, unfortunately. Sorry about that! And thank you so much for these updates! It is quite an honor to have you contributing on this project!

**Comment by stubailo** [comment]
@kahmali hey, no problem - it's your repo. Going to change those commit messages for you.

**Comment by stubailo** [comment]
Just updated, sorry for not reading your contributor guidelines carefully!

**Comment by kahmali** [comment]
No problem! Sorry for my mild psychosis! This looks perfect. Thanks for squashing those commits together, too. Even better. I'm going to go ahead and merge this in.

It would be awesome if you wanted to tackle the catchall route. I'm going to create an issue for it along with all the other items on the 0.7.0 roadmap later tonight. 

Thanks so much for replacing Iron Router! This is amazing. It will fix so many existing (and likely many future) issues.

**Comment by dandv** [comment]
@kahmali, your OCD is hilarious, but is [the apparently dying](https://forums.meteor.com/t/should-i-be-using-iron-router-or-is-it-dying/4540) iron-router removed? I see it [in package.js](https://github.com/kahmali/meteor-restivus/blob/devel/package.js#L17).

**Comment by stubailo** [comment]
@dandv I think version 0.7.0 is not yet shipped, that branch represents the older version.

**Pull request merged**
