### PR TITLE
for _the_ Items collection

### PR DESCRIPTION
**Pull request by dandv**

### CODE REVIEW

**Comment by kahmali** [comment]
Fix looks good. I just need the commit message updated to use the imperative `Fix typo`, or even better, `Fix typo in README`, and then I'll pull this in. You didn't think you were getting away without me nitpicking about _something_, right?

**Comment by dandv** [comment]
Let's see what happens with a PR whose commit was amended and force pushed :)

**Comment by kahmali** [comment]
Haha. I do that all the time (force push to a PR), so I know it works as expected. I also used my [improved merge strategy](https://github.com/kahmali/meteor-restivus/issues/89#issuecomment-117805045) to get the [super clean commit history](https://github.com/kahmali/meteor-restivus/commits/devel). Thanks again for the suggestion that got me there! We have to find a way to share this merge strategy with the world. It would definitely make the world a better place.

**Comment by dandv** [comment]
This PR merge strategy is one of those [things I wish were taught in school](http://wiki.dandascalescu.com/essays/things_i_wish_were_taught_in_school)!

**Pull request merged**
