### PR TITLE
Add info about plugins, list restivus-swagger.

### PR DESCRIPTION
**Pull request by jykae**
## Proposed changes
- add plugins info
- list apinf:restivus-swagger

@kahmali would appreciate adding our plugin for Restivus README :)

### CODE REVIEW

**Comment by kahmali** [comment]
Hi @jykae,

Thanks for submitting this PR. Love the plugin! Haven't had a chance to try it out but it looks great. I'm a fan of Swagger. 

I'm happy to merge this in as is, but I do have a few suggestions if you'd like to address them first:
- Move the **Plugins** to the top of the **Resources** section (since they're the sexiest of the current three options)
- Add a link to the [Swagger site](http://swagger.io/) when you mention it (for those that might be unfamiliar)
- Remove the period from the end of your commit message subject line (OK...this one is less a suggestion and more a [requirement](https://github.com/kahmali/meteor-restivus/blob/devel/CONTRIBUTING.md#commit-messages) to fit with the existing convention)

**Comment by jykae** [comment]
@kahmali Changes made. Can you live with the period in the first commit message? I did not use it in the next commits. I'll read through guidelines, thanks for the link.

**Comment by kahmali** [comment]
Hey @jykae! Thanks for the updates. The docs look good.  

You're probably gonna hate me after this, but I don't think I could sleep well at night with that commit message. I've held to my conventions for over a year now, and I don't think I'm ready to abandon them now. Sorry, but nobody is above my [git OCD](https://github.com/kahmali/meteor-restivus/issues/89), not even [members of MDG](https://github.com/kahmali/meteor-restivus/pull/46#issuecomment-98184151). While you're fixing that commit message up, please do me a favor and mention that it was an update to the README. You can use the subject line `Add plugins to README (list restivus-swagger)` or `Add restivus-swagger to new Plugins section of README` (I think I like that one more). Also, I would also prefer you [squash all those commits into one](https://github.com/kahmali/meteor-restivus/blob/devel/CONTRIBUTING.md#committing), since they're all related to a single minor update – no need for 4 commits there. Just take a look at the commit subject lines and scope of the commits in my [commit history](https://github.com/kahmali/meteor-restivus/commits/devel) and you'll quickly get a sense of my standards. Sorry for my psychosis! And thanks again for your work on the plugin!

**Comment by jykae** [comment]
Ok, there you go mr. @kahmali 🙇 
I hope I meet now the standards with this one neat commit. (Thanks, I learnt to use git rebase!)
Now I think I can sleep 💤

**Comment by kahmali** [comment]
Haha :) Awesome! I'll review and merge this in tonight. I'm sure it's ready to go. Thanks so much for the PR! You'll get a notification as soon as it's merged in.

**Comment by kahmali** [comment]
All set. Keep up the great work on the `restivus-swagger` package! Thanks!

**Comment by brylie** [comment]
:+1: :smiley:

**Pull request merged**
