### PR TITLE
Fix typo on documentation /post => /posts

### PR DESCRIPTION
**Pull request by lucasprag**
Also, fix issue #127

I just hope to help.

Thanks

### CODE REVIEW

**Comment by Lucasosf** [comment]
ping @kahmali

**Comment by lucasprag** [comment]
ping @kahmali

**Comment by lucasprag** [comment]
ping @kahmali

**Comment by lucasprag** [comment]
Is this project abandoned @kahmali ?

**Comment by lucasprag** [comment]
ping @kahmali

**Pull request closed without merging**
