### PR TITLE
Fix error response in default login endpoint

### PR DESCRIPTION
**Pull request by nicoonee**
Validate if user, password provided
Change error code to 400

### CODE REVIEW

**Comment by kahmali** [comment]
The code and commit message look great. Those _should_ be all set. Now we just need to add a simple automated test to make sure this actually works, and update the change log. You can just copy the test from [another error case](https://github.com/kahmali/meteor-restivus/blob/dev/test/api_tests.coffee#L77) and adapt it to suit your needs. You can `describe 'The default login endpoint'` (will need to be added). If you need any help with that just let me know. It should be pretty straightforward. The [change log](https://github.com/kahmali/meteor-restivus/blob/dev/CHANGELOG.md) should follow the style and convention of the rest of the change log. If you have any trouble with that, or English isn't your first language, just let me know and I'll write something up for you here. Thanks so much for the contribution! Almost there!

**Comment by nicoonee** [comment]
You want this test as separate pull request? or abandon this and put it all
together?

**Comment by kahmali** [comment]
You can do it with this same PR. Just add it in a separate commit and squash them together. Then force push to the same remote branch this PR is on. If you're not familiar with that process just let me know and I'll give you some more details. It's always best to submit PRs from a separate feature branch on your own repo. For that, you may want to create a new PR. That's just a good habit, in case you want to submit multiple changes. Whichever route you go, the fix and tests should definitely be a part of the same PR.

**Comment by nicoonee** [comment]
ok i made reset instead of rebase - gerrit habits ;)
ok there is all stuff in one PR let me know if all is fine

**Comment by nicoonee** [comment]
Oh yes true - fixed

**Comment by kahmali** [comment]
Alright, well let's start breaking you out of those terrible habits! :D I am very particular about my [commit history](https://github.com/kahmali/meteor-restivus/network) (just scroll through and you'll see that the history is completely linear except for merged PRs). I follow a very strict rebase strategy, breaking commits up into their appropriate chunks. I advise you to read through my commit history to get a feel for what I'm talking about. I love having contributors, but I don't want to start polluting my commit history. It's already gross enough having to `merge` PRs, but everything in between should be neatly rebased to allow for the cleanest history. Let me know if you need help squashing and rebasing this. I might not be able to respond again until tomorrow though, unfortunately. It's finals week and I have to get a bunch of work turned in by midnight EST. Thanks again for everything you've done so far. It's looking really good. I think we just need to clean up the history, then I'll test, bump the version, and publish the update. I can take care of updating the change log before I bump the version, if you'd like.

**Pull request closed without merging**
